#!/bin/sh

set -eu

device=$1

NL="
"

if [ ! -e "$device" ]; then
  echo "Device not found. ($device)" >&2
  exit 1
fi

if fdisk -l $1 | grep "^/dev" > /dev/null; then
  exit 0
fi

echo "Create partition. ($device)"
echo "n${NL}p${NL}1${NL}${NL}${NL}w" | fdisk $device > /dev/null
