#!/bin/sh

USERNAME=$1

PASSWORD=$(echo $USERNAME | openssl passwd -1 -stdin)

echo "Create login user '$USERNAME'"
id $USERNAME > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "user '$USERNAME' already exists, skipping."
else
  useradd -m -G adm,staff,vagrant -s /bin/bash -p $PASSWORD $USERNAME
  echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USERNAME
  mkdir -p /.ssh
  chown $USERNAME:$USERNAME /.ssh
fi
usermod -p $PASSWORD $USERNAME
