#!/bin/sh

NAME=$1
DIR=$2
OPTION=$3

if [ "$OPTION" = "--user" ]; then
    USERNAME=$4
    OPTION="uid=$USERNAME,gid=$USERNAME,fmode=644,dmode=755"
fi

if [ "$OPTION" = "--user-only" ]; then
    USERNAME=$4
    OPTION="uid=$USERNAME,gid=$USERNAME,fmode=600,dmode=700"
fi

if [ "$OPTION" != "" ]; then
    OPTION="-o $OPTION"
fi

mkdir -p $DIR

cat <<DATA >> /usr/local/sbin/shared-folder.sh
/bin/mount -t vboxsf $NAME $OPTION $DIR
DATA
