#!/bin/sh

DEVICE=$1
DIR=$2

MKPART=$(cat <<DATA
n
p
1


w
DATA
)

if [ -e $DEVICE ]; then
    if [ ! -e ${DEVICE}1 ]; then
        echo "Create partition. (${DEVICE}1 => $DIR)"
        echo "$MKPART" | fdisk $DEVICE > /dev/null
        mkfs.ext4 -q ${DEVICE}1

        if [ -d $DIR ]; then
            echo "Copying existing data."
            mount ${DEVICE}1 /mnt
            cp -a $DIR/* /mnt/
            umount /mnt
        else
            mkdir -p $DIR
        fi

        echo "${DEVICE}1 $DIR ext4 defaults 0 0" >> /etc/fstab
        mount -a
    fi
else
    echo "Not found device. ($DEVICE)" >&2
fi
