#!/bin/sh

if [ "$1" = "install" ]; then
cat <<DATA > /usr/local/sbin/shared-folder.sh
#!/bin/sh

DATA
chmod +x /usr/local/sbin/shared-folder.sh

cat <<DATA > /etc/systemd/system/shared-folder.service
[Unit]
Description=shared folder service
Requires=vboxadd-service.service
After=local-fs.target vboxadd-service.service vboxadd.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/shared-folder.sh

[Install]
WantedBy=multi-user.target
DATA

systemctl enable shared-folder.service
fi

if [ "$1" = "start" ]; then
systemctl restart shared-folder.service
fi