#!/bin/sh

while [ ${self=$0} ]; do
  cd "${self%/*}/"
  self=$(readlink "${self##*/}")
done

echo export VM_NAME=$1
echo export PATH=$(pwd):$PATH

cat <<'DATA'
load() {
  prog=$1
  target=$(target-path $prog)

  if [ "$target" ]; then
    echo "Load $prog: $target"

    cd "$(dirname $target)"
    . "$target"
  else
    echo "Load $prog: Not found" >&2
    exit 1
  fi
}
DATA
