#!/bin/sh

set -eu

device=$1

CR="
"

if [ ! -e "$device" ]; then
  echo "Device not found. ($device)" >&2
  exit 1
fi

if list-partitions "$1" > /dev/null; then
  exit 0
fi

echo "Create partition. ($device)"
echo "n${CR}p${CR}1${CR}${CR}${CR}w" | fdisk $device > /dev/null
