#!/bin/sh

set -eu

name=$1
device=$2
dir=$3

if [ "$(fstype $device)" ]; then
  exit 0
fi

echo "Formatting $device"
mkfs.ext4 -q $device

if [ -d $dir ]; then
  echo "Copying existing data."
  mount $device /mnt
  cp -a $dir/* /mnt/
  umount /mnt
else
  mkdir -p $dir
fi

e2label $device $name
echo "LABEL=$name $dir ext4 defaults 0 0" >> /etc/fstab
mount -a
