#!/bin/sh

prog=$1
shift

target=$(target-path "$prog")

if [ "$target" != "" ]; then
  echo "--------------------------------------------------"
  echo "Provide $prog: execute $target"

  cd "$(dirname $target)"
  "$target" "$@"
else
  echo "Provide $prog: Provider not found" >&2
  exit 1
fi
