#!/bin/sh

prog=$1
shift

target=""
if [ "$VM_NAME" != "" -a -e "/vagrant/$VM_NAME/$prog" ]; then
  target="/vagrant/$VM_NAME/$prog"
elif [ -e "/vagrant/.provisions/$prog" ]; then
  target="/vagrant/.provisions/$prog"
fi

if [ "$target" != "" ]; then
  echo "Provide $prog: execute $target"

  cd "$(dirname $target)"
  "$target" "$@"
else
  echo "Provide $prog: Provider not found" >&2
  exit 1
fi
